name: Build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-lambda
        run: pip install cargo-lambda

      - name: Build Lambda zip
        run: cargo lambda build --release --arm64

      - name: Archive bootstrap.zip
        uses: actions/upload-artifact@v4
        with:
          name: bootstrap
          path: target/lambda/alexa-smart-home-skill/
